[world]
name = "Cipher"
seed = "cipher_v5"

[namespace]
default = "cipher"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x05683819EFB8866D7A455b5C056003a78AF92B402dc38a12ccd5359cF765BaCd"
private_key = "0x031808887bae4fa4afecdcac8c632fe2c31f5a22937b20705e28364eec839d1f"

[writers]
"cipher" = ["cipher-actions"]
